import Link from "next/link";
import { TrendingUp } from "lucide-react";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <header className="border-b border-white/5 bg-background/80 backdrop-blur-xl px-6 py-4">
        <div className="mx-auto max-w-3xl flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2.5">
            <div className="flex h-7 w-7 items-center justify-center rounded-lg bg-gradient-to-br from-indigo-500 to-cyan-500">
              <TrendingUp className="h-3.5 w-3.5 text-white" />
            </div>
            <span className="text-sm font-bold">
              GrowthOS<span className="text-indigo-400">.travel</span>
            </span>
          </Link>
          <Link
            href="/"
            className="text-sm text-muted-foreground hover:text-foreground transition-colors"
          >
            ← Back to home
          </Link>
        </div>
      </header>

      <main className="mx-auto max-w-3xl px-6 py-16">
        <h1 className="text-3xl font-bold mb-2">Terms of Service</h1>
        <p className="text-sm text-muted-foreground mb-10">
          Last updated: May 2026
        </p>

        <div className="space-y-8 text-sm text-muted-foreground leading-relaxed">
          <section>
            <h2 className="text-base font-semibold text-foreground mb-3">
              1. Acceptance of Terms
            </h2>
            <p>
              By creating an account or using GrowthOS.travel, you agree to
              these Terms of Service. If you do not agree, please do not use the
              platform.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground mb-3">
              2. Description of Service
            </h2>
            <p>
              GrowthOS.travel provides AI-powered growth audits, competitor
              analysis, and recommendations for travel businesses in India. The
              platform analyses publicly available data about your business and
              competitors to generate actionable insights.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground mb-3">
              3. Account Responsibilities
            </h2>
            <p>
              You are responsible for maintaining the security of your account
              credentials. You must provide accurate business information when
              registering. You may not use the platform for any unlawful purpose
              or to audit websites you do not own or have permission to audit.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground mb-3">
              4. Subscription and Billing
            </h2>
            <p>
              Free plan users receive 3 audits per month. Pro and Agency plans
              are billed monthly or annually as selected at checkout. You may
              cancel your subscription at any time; cancellation takes effect at
              the end of the current billing period. No refunds for partial
              months.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground mb-3">
              5. Accuracy of Audit Results
            </h2>
            <p>
              Audit results are generated by AI and are provided for
              informational purposes. GrowthOS.travel does not guarantee
              specific business outcomes from following recommendations. Results
              are based on publicly available data and may not reflect all
              aspects of your business.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground mb-3">
              6. Intellectual Property
            </h2>
            <p>
              Audit reports generated for your business are yours to use. The
              GrowthOS.travel platform, algorithms, and branding remain the
              exclusive property of GrowthOS.travel. You may not reproduce or
              resell platform outputs as your own product.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground mb-3">
              7. Limitation of Liability
            </h2>
            <p>
              GrowthOS.travel is not liable for any indirect, incidental, or
              consequential damages arising from use of the platform. Our total
              liability to you shall not exceed the amount you paid in the 3
              months preceding the claim.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground mb-3">
              8. Termination
            </h2>
            <p>
              We reserve the right to suspend or terminate accounts that violate
              these terms, misuse the platform, or engage in fraudulent
              activity.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground mb-3">
              9. Changes to Terms
            </h2>
            <p>
              We may update these terms from time to time. Continued use of the
              platform after changes are posted constitutes your acceptance of
              the updated terms.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground mb-3">
              10. Contact
            </h2>
            <p>
              For questions about these terms, contact us at{" "}
              <a
                href="mailto:legal@growthos.travel"
                className="text-indigo-400 hover:underline"
              >
                legal@growthos.travel
              </a>
              .
            </p>
          </section>
        </div>
      </main>

      <footer className="border-t border-border py-6 px-6 text-center text-xs text-muted-foreground">
        © 2026 GrowthOS.travel ·{" "}
        <Link href="/terms" className="hover:text-foreground transition-colors">
          Terms
        </Link>
        {" · "}
        <Link
          href="/privacy"
          className="hover:text-foreground transition-colors"
        >
          Privacy
        </Link>
      </footer>
    </div>
  );
}
